language: c
script: ./configure ${CONFIG_OPTS} && make -k W=1 ${MAKE_FLAGS}
dist: trusty
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux

    - os: linux
      env:
        - MATRIX_EVAL="CC=clang"

    - os: linux
      env:
        - MATRIX_EVAL="CFLAGS=-m32 && LDFLAGS=-m32"

    - os: linux
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
      env:
        - CONFIG_OPTS="--host x86_64-w64-mingw32"
        - MATRIX_EVAL="CC=x86_64-w64-mingw32-gcc"

    - os: linux
      addons:
        apt:
          packages:
            - gcc-mingw-w64-i686
            - mingw-w64-i686-dev
      env:
        - CONFIG_OPTS="--host i686-w64-mingw32"
        - MATRIX_EVAL="CC=i686-w64-mingw32-gcc"

    - os: linux
      install:
        - git clone https://git.kernel.org/pub/scm/devel/sparse/sparse.git --branch v0.5.2
        - pushd sparse && make HAVE_LLVM=no && sudo make install HAVE_LLVM=no && popd
      env:
        - MATRIX_EVAL="CC=cgcc"
        - MAKE_FLAGS="CFLAGS=-Wsparse-error CFLAGS+=-Wno-vla CFLAGS+=-Wno-old-initializer"

before_script:
    - if [ "$CC" = i686-w64-mingw32-gcc ]; then
          sudo ln -s /usr/bin/i686_64-w64-mingw32-windres /usr/bin/windres;
          wget -c https://www.openssl.org/source/openssl-1.0.2p.tar.gz;
          tar -xzvf openssl-1.0.2p.tar.gz;
          cd openssl-1.0.2p/;
          ./Configure --prefix=/usr/i686_64-w64-mingw32 --openssldir=/usr/i686_64-w64-mingw32 --cross-compile-prefix=/usr/bin/ mingw;
          make depend;
          make;
          sudo make install ;
          ls /usr/i686_64-w64-mingw32/include;
          ls /usr/i686_64-w64-mingw32/lib;
	  $CC -print-search-dirs | sed '/^lib/b 1;d;:1;s,/[^/.][^/]*/\.\./,/,;t 1;s,:[^=]*=,:;,;s,;,;  ,g' | tr \; \\012
          cd ..;
      elif [ "$CC" = x86_64-w64-mingw32-gcc ]; then
          sudo ln -s /usr/bin/x86_64-w64-mingw32-windres /usr/bin/windres;
          wget -c https://www.openssl.org/source/openssl-1.0.2p.tar.gz;
          tar -xzvf openssl-1.0.2p.tar.gz;
          cd openssl-1.0.2p/;
          ./Configure --prefix=/usr/x86_64-w64-mingw32 --openssldir=/usr/x86_64-w64-mingw32 --cross-compile-prefix=/usr/bin/ mingw64;
          make depend;
          make;
          sudo make install ;
          cd ..;
      fi
before_install:
    - eval "${MATRIX_EVAL}"


notifications:
  email:
    recipients:
      - logang@deltatee.com
